### ISSUE TITLE
Invalid oauth url

### ISSUE THREAD

**Issue by vansh705** [AngeloCore/uptimer#1]
When I try to login it shows invalid oauth2 url

**Comment by AngeloCore** [comment]
Go to config.json

```json
"login": {
    "id": "",
    "secret": ""
  }
```

On id:
 Go to discord.com/developers
Create application or use exits, copy your client id and paste 
Example

```json
"login": {
    "id": "123456789123456789",
    "secret": ""
  }
```

On secret:
Copy your client secret and paste 
Exmple

```json
"login": {
    "id": "12345678923456789",
    "secret": "client secret"
  }
```

Go to Oauth2 section on the sidebar of your application
And add: https://yourdomain.com/callback

![Screenshot_20210324_134459_com huawei browser](https://user-images.githubusercontent.com/62988428/112305336-3d408e00-8ca7-11eb-99bb-77f3ba9894b2.png)

**Comment by AngeloCore** [comment]
Worked?

**Comment by zanedeveloper** [comment]
yep
