### ISSUE TITLE
will not work on replit.com

### ISSUE THREAD

**Issue by Fantom-XR** [AngeloCore/uptimer#2]
It will not start on replit.com.

**Comment by AngeloCore** [comment]
Whats your repl language?

**Comment by Fantom-XR** [comment]
Node.JS
![image](https://user-images.githubusercontent.com/52836243/118704013-9859b180-b80e-11eb-9489-d428dc86345c.png)

**Comment by AngeloCore** [comment]
What is your error?

**Comment by AngeloCore** [comment]
@Fantom-XR

**Comment by Fantom-XR** [comment]
![image](https://user-images.githubusercontent.com/52836243/118799773-0649bb80-b897-11eb-99b5-7ea77b78d415.png)

![image](https://user-images.githubusercontent.com/52836243/118799782-0ba70600-b897-11eb-97f0-babaf911f475.png)

**Comment by AngeloCore** [comment]
What is your nodejs version?
You can check quickly using the shell, write `node -v`

**Comment by Fantom-XR** [comment]
v12.22.1

**Comment by NodoY5** [comment]
I too have the same problem bro

**Comment by AngeloCore** [comment]
Just go to the "Shell" and type this: `npm i quick.db`

**Comment by Fantom-XR** [comment]
That doesnt even work, it comes up with errors.

**Comment by AngeloCore** [comment]
Ok try `npm i better-sqlite3`
In the shell not in the console

**Comment by Fantom-XR** [comment]
Got this.
![image](https://user-images.githubusercontent.com/52836243/119224129-eadbec00-baf4-11eb-839d-276b60f68254.png)

**Comment by cursorweb** [comment]
use the bash language instead

**Comment by NodoY5** [comment]
It works my side
